/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto1.bingo;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import proyecto1.logicadenegocios.CuentaCorreo;
import proyecto1.logicadenegocios.Juego;
import proyecto1.logicadenegocios.Jugador;

/**
 *
 * @author Daniel
 */
public class enviarCartones extends javax.swing.JFrame {

    /**
     * Creates new form enviarCartones
     */
    public enviarCartones() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cedula = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        BTNEnviar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Enviar cartones");

        jLabel2.setText("Digite la cédula del jugador:");

        cedula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cedula.setSelectedItem(cedula);
        cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaActionPerformed(evt);
            }
        });

        jLabel3.setText("Digite la cantidad de cartones:");

        cantidad.setText("0");
        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });

        BTNEnviar.setText("Enviar");
        BTNEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEnviarActionPerformed(evt);
            }
        });

        jButton2.setText("Regresar");
        jButton2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                jButton2AncestorRemoved(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(BTNEnviar)))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(siguiente)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(BTNEnviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(siguiente))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public static Juego juego;
    
    
    public Juego cargarDatos(Juego juegoEnCurso){
        juego=juegoEnCurso;
        return juego;
    }
    
    
     
    private void BTNEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEnviarActionPerformed
        try {
            String selectedCedula = (String) cedula.getSelectedItem();
            int cedula2=Integer.parseInt(selectedCedula);
            String numCartonesStr = cantidad.getText(); 

            if(selectedCedula != null && numCartonesStr != null && !selectedCedula.isEmpty() && !numCartonesStr.isEmpty()) {
                int numCartones = Integer.parseInt(numCartonesStr);
                String correo=cargarCorreoSeleccionado(cedula2);
                juego.asignarCartonesAJugador(cedula2, numCartones);

                // Enviar los cartones por correo
                String[] archivosAdjuntos=tomarImagenes(numCartones);
                CuentaCorreo cuentaCorreo = new CuentaCorreo("gestorbingos@gmail.com");
                cuentaCorreo.enviarCorreo(correo, archivosAdjuntos);
                JOptionPane.showMessageDialog(this, "Cartones enviados con éxito.");

                }
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Debe ingresar un número válido.");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_BTNEnviarActionPerformed

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed

    private void cargarCedulasEnComboBox() {
        List<Jugador> jugadores = juego.getJugadores();
        DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();

        for (Jugador jugador : jugadores) {
            int cedula1 = jugador.getCedula();
            String cedulaString = String.valueOf(cedula1);
            
            modelo.addElement(cedulaString);
        }

        cedula.setModel(modelo);
    }
    
    private String cargarCorreoSeleccionado(int cedula) {
        List<Jugador> jugadores = juego.getJugadores();

        for (Jugador jugador : jugadores) {
            if (jugador.getCedula() == cedula) {
                return jugador.getCorreo();
            }
        }

        // Si no se encuentra un jugador con la cédula especificada, retorna null o una cadena vacía
        return null;
    }
    

    private String[] tomarImagenes(int numCartones) {
        // Dirección de la carpeta
        File carpeta = new File("C:/Users/Daniel/Documents/GitHub/PP1---POO/Proyecto1-Bingo/src/Cartones/");

        // Lista de todos los archivos en la carpeta
        File[] archivos = carpeta.listFiles((dir, name) -> name.toLowerCase().endsWith(".jpg"));

        // Si la carpeta no tiene archivos o hay un error, retornamos un arreglo vacío
        if (archivos == null || archivos.length == 0) {
            return new String[0];
        }

        // Determinar el número de archivos a tomar
        int archivosATomar = Math.min(numCartones, archivos.length);

        // Crear un arreglo para almacenar las rutas de los archivos seleccionados
        String[] rutasSeleccionadas = new String[archivosATomar];

        // Tomar las primeras numCartones imágenes
        for (int i = 0; i < archivosATomar; i++) {
            rutasSeleccionadas[i] = archivos[i].getPath();
        }

        return rutasSeleccionadas;
    }

      

         

    

    
    
    
    private void cedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaActionPerformed
        cargarCedulasEnComboBox();
    }//GEN-LAST:event_cedulaActionPerformed

    private void jButton2AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButton2AncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2AncestorRemoved

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        index volver = new index();
        volver.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        IniciarJuegoJFrame a = new IniciarJuegoJFrame();
        a.cargarDatos(juego);
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_siguienteActionPerformed

    
     /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerarCartones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerarCartones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerarCartones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerarCartones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new enviarCartones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNEnviar;
    private javax.swing.JTextField cantidad;
    private javax.swing.JComboBox<String> cedula;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton siguiente;
    // End of variables declaration//GEN-END:variables
}
