/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1.bingo;


import java.util.List;
import java.awt.Dimension;
import java.awt.BorderLayout;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import proyecto1.dao.numerosCantados;



/**
 *
 * @author Dell
 */
public class Top10Numeros extends javax.swing.JFrame {

    /**
     * Creates new form Top10Numeros
     */
    public Top10Numeros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jButton2.setText("Generar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Paso 1: Obtener los datos de la base de datos 
            // int T1= x 10 (numero)
        numerosCantados dataList= new numerosCantados();   
        List<Integer> top10= dataList.top10();
        DefaultCategoryDataset datos= new DefaultCategoryDataset();
        
        
        int T1= top10.get(0);
        int cantidadDeVeces1=top10.get(1);
        String datoT1= String.valueOf(T1);
        datos.setValue(cantidadDeVeces1,datoT1, "Número");
        
        int T2= top10.get(2);
        int cantidadDeVeces2=top10.get(3);
        String datoT2= String.valueOf(T2);
        datos.setValue(cantidadDeVeces2,datoT2, "Número");
        
        int T3= top10.get(4);
        int cantidadDeVeces3=top10.get(5);
        String datoT3= String.valueOf(T3);
        datos.setValue(cantidadDeVeces3,datoT3, "Número");
        
        int T4= top10.get(6);
        int cantidadDeVeces4=top10.get(7);
        String datoT4= String.valueOf(T4);
        datos.setValue(cantidadDeVeces4,datoT4, "Número");
        
        int T5= top10.get(8);
        int cantidadDeVeces5=top10.get(9);
        String datoT5= String.valueOf(T5);
        datos.setValue(cantidadDeVeces5,datoT5, "Número");
        
        int T6= top10.get(10);
        int cantidadDeVeces6=top10.get(11);
        String datoT6= String.valueOf(T6);
        datos.setValue(cantidadDeVeces6,datoT6, "Número");
        
        int T7= top10.get(12);
        int cantidadDeVeces7=top10.get(13);
        String datoT7= String.valueOf(T7);
        datos.setValue(cantidadDeVeces7,datoT7, "Número");
        
        int T8= top10.get(14);
        int cantidadDeVeces8=top10.get(15);
        String datoT8= String.valueOf(T8);
        datos.setValue(cantidadDeVeces8,datoT8, "Número");
        
        int T9= top10.get(16);
        int cantidadDeVeces9=top10.get(17);
        String datoT9= String.valueOf(T9);
        datos.setValue(cantidadDeVeces9,datoT9, "Número");
        
        int T10= top10.get(18);
        int cantidadDeVeces10=top10.get(19);
        String datoT10= String.valueOf(T10);
        datos.setValue(cantidadDeVeces10,datoT10, "Número");
        
        
        JFreeChart graficoBarras= ChartFactory.createBarChart3D(
            "Top 10 números cantados", //nombre del grafico5
            "Números", //nombre de las barras
            "Cant. coincidencias", // nombre de la numeración
            datos, //datos del gráfico
            PlotOrientation.VERTICAL, //Horientación
            true, //leyenda de barras individuales por color
            true, //herramientas
            false //url del grafico
        
        );
        
        ChartPanel panel= new ChartPanel (graficoBarras);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(550,200));
        
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(panel,BorderLayout.NORTH);
        
        pack();
        repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        index a = new index();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Top10Numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Top10Numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Top10Numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Top10Numeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Top10Numeros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
